/*
 * Copyright 2014-2015 Victor Osolovskiy, Sergey Navrotskiy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ftldb.ext;


import freemarker.core.Environment;
import freemarker.template.TemplateMethodModelEx;
import freemarker.template.TemplateModelException;

import java.util.List;


/**
 * This class implements an FTL method named {@code template_name} that returns the current template name. No arguments
 * are needed.
 *
 * <p>Method definition: {@code String template_name()}
 *
 * <p>Usage examples in FTL:
 * <pre>
 * {@code
 * generated by template "${template_name()}"
 * }
 * </pre>
 */
public class TemplateNameMethod implements TemplateMethodModelEx {


    public Object exec(List args) throws TemplateModelException {
        if (args.size() != 0) {
            throw new TemplateModelException("No arguments needed");
        }
        return Environment.getCurrentEnvironment().getCurrentTemplate().getName();
    }


}
